// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEkYFn_YVY01ImfaNvK-eaqlWZ_eSN3ms',
    appId: '1:63893371649:web:20f9bd245c7201da76f900',
    messagingSenderId: '63893371649',
    projectId: 'city-quest-fc092',
    authDomain: 'city-quest-fc092.firebaseapp.com',
    storageBucket: 'city-quest-fc092.firebasestorage.app',
    measurementId: 'G-6CH1B64ZK4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKf_CpX4ZeGHwr3ISBYlxnndOKpI--DkU',
    appId: '1:63893371649:android:cff13a0f4d0d225676f900',
    messagingSenderId: '63893371649',
    projectId: 'city-quest-fc092',
    storageBucket: 'city-quest-fc092.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYaCjahUgCTGoDrE8RqtasmyCKW3XyHeE',
    appId: '1:63893371649:ios:d36d2af767a0171076f900',
    messagingSenderId: '63893371649',
    projectId: 'city-quest-fc092',
    storageBucket: 'city-quest-fc092.firebasestorage.app',
    iosBundleId: 'com.example.cityQuest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYaCjahUgCTGoDrE8RqtasmyCKW3XyHeE',
    appId: '1:63893371649:ios:d36d2af767a0171076f900',
    messagingSenderId: '63893371649',
    projectId: 'city-quest-fc092',
    storageBucket: 'city-quest-fc092.firebasestorage.app',
    iosBundleId: 'com.example.cityQuest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEkYFn_YVY01ImfaNvK-eaqlWZ_eSN3ms',
    appId: '1:63893371649:web:00960b0623fd191176f900',
    messagingSenderId: '63893371649',
    projectId: 'city-quest-fc092',
    authDomain: 'city-quest-fc092.firebaseapp.com',
    storageBucket: 'city-quest-fc092.firebasestorage.app',
    measurementId: 'G-HTJBFZC7D0',
  );
}
